version: '3.8'

services:
  catalogdb:
    image: postgres:15
    container_name: catalogdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: catalogdb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - catalogdb_data:/var/lib/postgresql/data

volumes:
  catalogdb_data:

